@api = http://localhost:3000

GET {{api}}/videos

###
GET {{api}}/videos/5fa6fa8de431b72a8f518cbf

###
POST {{api}}/videos
Content-Type: application/json

{
  "url": "https://www.youtube.com/watch?v=ry1hpm1GXVI",
  "title": "Binary Numbers",
  "description": "Binary Numbers"
}

###
POST {{api}}/videos
Content-Type: application/json

{
  "url": "https://www.youtube.com/watch?v=OFwskHrtYQ4",
  "title": "Quantum Wavefunction",
  "description": "Quantum Wavefunction"
}

###
DELETE  {{api}}/videos/5fa6fa8de431b72a8f518cbf

###
PUT {{api}}/videos/5fa7015508232a39b4411e65
Content-Type: application/json

{
  "title": "Quantum Wavefunction (updated 2)"
}